const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

const Violation = sequelize.define('Violation', {
  id: {
    type: DataTypes.INTEGER.UNSIGNED,
    primaryKey: true,
    autoIncrement: true
  },
  zoneId: {
    type: DataTypes.INTEGER.UNSIGNED,
    allowNull: false,
    field: 'zone_id',
    references: {
      model: 'parking_zones',
      key: 'id'
    }
  },
  severity: {
    type: DataTypes.ENUM('warning', 'critical'),
    allowNull: false,
    defaultValue: 'warning'
  },
  excessVehicles: {
    type: DataTypes.INTEGER,
    allowNull: false,
    field: 'excess_vehicles',
    defaultValue: 0
  },
  penaltyAmount: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: false,
    field: 'penalty_amount',
    defaultValue: 0
  },
  timestamp: {
    type: DataTypes.DATE,
    defaultValue: DataTypes.NOW,
    field: 'timestamp'
  },
  resolved: {
    type: DataTypes.BOOLEAN,
    defaultValue: false,
    field: 'resolved'
  },
  resolvedAt: {
    type: DataTypes.DATE,
    field: 'resolved_at'
  },
  notes: {
    type: DataTypes.TEXT
  },
  autoGenerated: {
    type: DataTypes.BOOLEAN,
    defaultValue: true,
    field: 'auto_generated'
  }
}, {
  tableName: 'violations',
  timestamps: false
});

module.exports = Violation;
