const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

const Violation = sequelize.define('Violation', {
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true
  },
  zoneId: {
    type: DataTypes.INTEGER,
    allowNull: false,
    field: 'zone_id',
    references: {
      model: 'parking_zones',
      key: 'id'
    }
  },
  severity: {
    type: DataTypes.ENUM('critical', 'warning'),
    allowNull: false,
    defaultValue: 'warning'
  },
  status: {
    type: DataTypes.ENUM('pending', 'resolved', 'paid'),
    allowNull: false,
    defaultValue: 'pending'
  },
  excessVehicles: {
    type: DataTypes.INTEGER,
    allowNull: false,
    field: 'excess_vehicles',
    defaultValue: 0
  },
  penaltyAmount: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: false,
    field: 'penalty_amount',
    defaultValue: 0
  },
  uniqueCode: {
    type: DataTypes.STRING(20),
    unique: true,
    field: 'unique_code'
  },
  resolvedAt: {
    type: DataTypes.DATE,
    field: 'resolved_at'
  },
  resolvedBy: {
    type: DataTypes.INTEGER,
    field: 'resolved_by',
    references: {
      model: 'users',
      key: 'id'
    }
  },
  notes: {
    type: DataTypes.TEXT
  },
  isPaid: {
    type: DataTypes.BOOLEAN,
    defaultValue: false,
    field: 'is_paid'
  },
  autoGenerated: {
    type: DataTypes.BOOLEAN,
    defaultValue: true,
    field: 'auto_generated'
  },
  timestamp: {
    type: DataTypes.DATE,
    defaultValue: DataTypes.NOW,
    field: 'timestamp'
  }
}, {
  tableName: 'violations',
  timestamps: true,
  createdAt: 'timestamp',
  updatedAt: 'updated_at',
  underscored: true
});

module.exports = Violation;
