const express = require('express');
const router = express.Router();
const { Violation, ParkingZone, sequelize } = require('../models');
const { Op } = require('sequelize');
const { authenticate, authorize } = require('../middlewares/auth.middleware');

// CSV Export route - must be before parameterized routes
router.get('/export', authenticate, authorize('admin', 'officer'), async (req, res, next) => {
  const violationController = require('../controllers/violation.controller');
  return violationController.exportViolations(req, res, next);
});

// Get all violations with filters
router.get('/', async (req, res, next) => {
  try {
    const { 
      status, 
      severity,
      zoneId, 
      zoneName,
      startDate, 
      endDate, 
      minPenalty, 
      maxPenalty
    } = req.query;
    
    const whereConditions = {};
    
    // Status filter (mapped to resolved)
    if (status === 'pending') {
      whereConditions.resolved = false;
    } else if (status === 'resolved') {
      whereConditions.resolved = true;
    }
    
    // Severity filter
    if (severity) {
      whereConditions.severity = severity;
    }

    if (zoneId) whereConditions.zoneId = zoneId;

    const include = [{
      model: ParkingZone,
      as: 'zone',
      attributes: ['id', 'name', 'address', 'contractorName']
    }];

    // Search by zone name
    if (zoneName) {
      include[0].where = {
        name: { [Op.like]: `%${zoneName}%` }
      };
    }
    
    if (startDate || endDate) {
      whereConditions.timestamp = {};
      if (startDate) whereConditions.timestamp[Op.gte] = new Date(startDate);
      if (endDate) whereConditions.timestamp[Op.lte] = new Date(endDate);
    }
    
    if (minPenalty || maxPenalty) {
      whereConditions.penaltyAmount = {};
      if (minPenalty) whereConditions.penaltyAmount[Op.gte] = parseFloat(minPenalty);
      if (maxPenalty) whereConditions.penaltyAmount[Op.lte] = parseFloat(maxPenalty);
    }

    const violations = await Violation.findAll({
      where: whereConditions,
      include,
      order: [['timestamp', 'DESC']]
    });
    
    res.json({
      success: true,
      count: violations.length,
      data: violations
    });
  } catch (error) {
    next(error);
  }
});

// Get single violation
router.get('/:id', async (req, res, next) => {
  try {
    const violation = await Violation.findByPk(req.params.id, {
      include: [{
        model: ParkingZone,
        as: 'zone',
        attributes: ['id', 'name', 'address', 'contractorName', 'penaltyPerVehicle']
      }]
    });
    
    if (!violation) {
      return res.status(404).json({
        success: false,
        error: 'Violation not found'
      });
    }
    
    res.json({
      success: true,
      data: violation
    });
  } catch (error) {
    next(error);
  }
});

// Create new violation (officer and admin only)
router.post('/', authenticate, authorize('admin', 'officer'), async (req, res, next) => {
  try {
    const { zoneId, excessVehicles, notes } = req.body;
    
    const zone = await ParkingZone.findByPk(zoneId);
    
    if (!zone) {
      return res.status(404).json({
        success: false,
        error: 'Parking zone not found'
      });
    }
    
    const penaltyPerVehicle = zone.penaltyPerVehicle || 500;
    const contractorLimit = zone.contractorLimit || 0;
    const penaltyAmount = excessVehicles * penaltyPerVehicle;
    const severity = excessVehicles > contractorLimit * 0.3 ? 'critical' : 'warning';
    
    const violation = await Violation.create({
      zoneId,
      excessVehicles,
      penaltyAmount,
      severity,
      notes,
      resolved: false,
      autoGenerated: false
    });
    
    res.status(201).json({
      success: true,
      message: 'Violation recorded successfully',
      data: violation
    });
  } catch (error) {
    next(error);
  }
});

// Resolve violation (officer and admin only)
router.patch('/:id/resolve', authenticate, authorize('admin', 'officer'), async (req, res, next) => {
  const violationController = require('../controllers/violation.controller');
  return violationController.resolveViolation(req, res, next);
});

// Update violation (officer and admin only)
router.put('/:id', authenticate, authorize('admin', 'officer'), async (req, res, next) => {
  try {
    const violation = await Violation.findByPk(req.params.id);
    
    if (!violation) {
      return res.status(404).json({
        success: false,
        error: 'Violation not found'
      });
    }
    
    // Recalculate penalty if excess vehicles changed
    const { excessVehicles } = req.body;
    const inputData = { ...req.body };
    const currentExcessVehicles = violation.excessVehicles || 0;
    
    if (excessVehicles && excessVehicles !== currentExcessVehicles) {
      const zoneId = violation.zoneId;
      const zone = await ParkingZone.findByPk(zoneId);
      if (zone) {
        const penaltyPerVehicle = zone.penaltyPerVehicle || 500;
        inputData.penaltyAmount = excessVehicles * penaltyPerVehicle;
      }
    }
    
    await violation.update(inputData);
    
    res.json({
      success: true,
      message: 'Violation updated successfully',
      data: violation
    });
  } catch (error) {
    next(error);
  }
});

// Delete violation (admin only)
router.delete('/:id', authenticate, authorize('admin'), async (req, res, next) => {
  try {
    const violation = await Violation.findByPk(req.params.id);
    
    if (!violation) {
      return res.status(404).json({
        success: false,
        error: 'Violation not found'
      });
    }
    
    await violation.destroy();
    
    res.json({
      success: true,
      message: 'Violation deleted successfully'
    });
  } catch (error) {
    next(error);
  }
});

// Get violation statistics (officer and admin only)
router.get('/stats/summary', authenticate, authorize('admin', 'officer'), async (req, res, next) => {
  try {
    const stats = await Violation.findAll({
      attributes: [
        [sequelize.fn('COUNT', sequelize.col('id')), 'totalViolations'],
        [sequelize.fn('SUM', sequelize.col('penalty_amount')), 'totalPenaltyAmount'],
        [sequelize.fn('SUM', sequelize.col('excess_vehicles')), 'totalExcessVehicles'],
        [sequelize.literal("COUNT(CASE WHEN resolved = 0 THEN 1 END)"), 'pendingViolations'],
        [sequelize.literal("COUNT(CASE WHEN resolved = 1 THEN 1 END)"), 'resolvedViolations'],
        [sequelize.literal("COUNT(CASE WHEN severity = 'critical' THEN 1 END)"), 'criticalViolations'],
        [sequelize.literal("COUNT(CASE WHEN severity = 'warning' THEN 1 END)"), 'warningViolations']
      ],
      raw: true
    });
    
    // Top 5 violating zones
    const topZones = await Violation.findAll({
      attributes: [
        'zone_id',
        [sequelize.fn('COUNT', sequelize.col('Violation.id')), 'count']
      ],
      include: [{
        model: ParkingZone,
        as: 'zone',
        attributes: ['name']
      }],
      group: ['zone_id', 'zone.id', 'zone.name'],
      order: [[sequelize.literal('count'), 'DESC']],
      limit: 5
    });

    res.json({
      success: true,
      data: {
        summary: stats[0],
        topZones
      }
    });
  } catch (error) {
    next(error);
  }
});

// Get violations by zone
router.get('/zone/:zoneId', async (req, res, next) => {
  try {
    const zone = await ParkingZone.findByPk(req.params.zoneId);
    
    if (!zone) {
      return res.status(404).json({
        success: false,
        error: 'Parking zone not found'
      });
    }
    
    const violations = await Violation.findAll({
      where: { zoneId: req.params.zoneId },
      include: [{
        model: ParkingZone,
        as: 'zone',
        attributes: ['id', 'name', 'address']
      }],
      order: [['timestamp', 'DESC']]
    });
    
    res.json({
      success: true,
      zone: {
        id: zone.id,
        name: zone.name,
        address: zone.address
      },
      count: violations.length,
      data: violations
    });
  } catch (error) {
    next(error);
  }
});

module.exports = router;
